import type { Dimension, DateDimension, Attribute, DataSourceInfo } from '@sisense/sdk-data';
import { createAttribute, createDateDimension, createDimension } from '@sisense/sdk-data';

export const DataSource: DataSourceInfo = { title: 'SaaS_Sample', type: 'elasticube' };

// Generated by Sisense SDK CLI — expressions match the actual ElastiCube table
interface SaasMetricsDimension extends Dimension {
  date: DateDimension;
  signup_date: DateDimension;
  cac: Attribute;
  company_name: Attribute;
  customer_id: Attribute;
  industry: Attribute;
  is_active: Attribute;
  is_churned: Attribute;
  is_new: Attribute;
  ltv: Attribute;
  mrr: Attribute;
  nps_score: Attribute;
  plan_tier: Attribute;
  team_size_bucket: Attribute;
}

const saasmetrics_csv = createDimension({
  name: 'saas-metrics.csv',
  date: createDateDimension({
    name: 'date',
    expression: '[saas-metrics.csv.date (Calendar)]',
    dataSource: { title: 'SaaS_Sample', live: false },
  }),
  signup_date: createDateDimension({
    name: 'signup_date',
    expression: '[saas-metrics.csv.signup_date (Calendar)]',
    dataSource: { title: 'SaaS_Sample', live: false },
  }),
  cac: createAttribute({
    name: 'cac',
    type: 'numeric-attribute',
    expression: '[saas-metrics.csv.cac]',
    dataSource: { title: 'SaaS_Sample', live: false },
  }),
  company_name: createAttribute({
    name: 'company_name',
    type: 'text-attribute',
    expression: '[saas-metrics.csv.company_name]',
    dataSource: { title: 'SaaS_Sample', live: false },
  }),
  customer_id: createAttribute({
    name: 'customer_id',
    type: 'numeric-attribute',
    expression: '[saas-metrics.csv.customer_id]',
    dataSource: { title: 'SaaS_Sample', live: false },
  }),
  industry: createAttribute({
    name: 'industry',
    type: 'text-attribute',
    expression: '[saas-metrics.csv.industry]',
    dataSource: { title: 'SaaS_Sample', live: false },
  }),
  is_active: createAttribute({
    name: 'is_active',
    type: 'numeric-attribute',
    expression: '[saas-metrics.csv.is_active]',
    dataSource: { title: 'SaaS_Sample', live: false },
  }),
  is_churned: createAttribute({
    name: 'is_churned',
    type: 'numeric-attribute',
    expression: '[saas-metrics.csv.is_churned]',
    dataSource: { title: 'SaaS_Sample', live: false },
  }),
  is_new: createAttribute({
    name: 'is_new',
    type: 'numeric-attribute',
    expression: '[saas-metrics.csv.is_new]',
    dataSource: { title: 'SaaS_Sample', live: false },
  }),
  ltv: createAttribute({
    name: 'ltv',
    type: 'numeric-attribute',
    expression: '[saas-metrics.csv.ltv]',
    dataSource: { title: 'SaaS_Sample', live: false },
  }),
  mrr: createAttribute({
    name: 'mrr',
    type: 'numeric-attribute',
    expression: '[saas-metrics.csv.mrr]',
    dataSource: { title: 'SaaS_Sample', live: false },
  }),
  nps_score: createAttribute({
    name: 'nps_score',
    type: 'numeric-attribute',
    expression: '[saas-metrics.csv.nps_score]',
    dataSource: { title: 'SaaS_Sample', live: false },
  }),
  plan_tier: createAttribute({
    name: 'plan_tier',
    type: 'text-attribute',
    expression: '[saas-metrics.csv.plan_tier]',
    dataSource: { title: 'SaaS_Sample', live: false },
  }),
  team_size_bucket: createAttribute({
    name: 'team_size_bucket',
    type: 'text-attribute',
    expression: '[saas-metrics.csv.team_size_bucket]',
    dataSource: { title: 'SaaS_Sample', live: false },
  }),
}) as SaasMetricsDimension;

// Re-export with PascalCase aliases so components don't need to change
export const DM = {
  Date: saasmetrics_csv.date,
  SignupDate: saasmetrics_csv.signup_date,
  Cac: saasmetrics_csv.cac,
  CompanyName: saasmetrics_csv.company_name,
  CustomerId: saasmetrics_csv.customer_id,
  Industry: saasmetrics_csv.industry,
  IsActive: saasmetrics_csv.is_active,
  IsChurned: saasmetrics_csv.is_churned,
  IsNew: saasmetrics_csv.is_new,
  Ltv: saasmetrics_csv.ltv,
  Mrr: saasmetrics_csv.mrr,
  NpsScore: saasmetrics_csv.nps_score,
  PlanTier: saasmetrics_csv.plan_tier,
  TeamSizeBucket: saasmetrics_csv.team_size_bucket,
};
